# Generated by Django 5.1.5 on 2025-04-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pessoa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_comercial", models.CharField(max_length=255)),
                ("principio_ativo", models.CharField(max_length=255)),
                ("fabricante", models.CharField(max_length=255)),
                ("forma_farmaceutica", models.CharField(max_length=100)),
                ("dosagem", models.CharField(max_length=50)),
                ("codigo_barras", models.CharField(max_length=50, unique=True)),
                ("receita_obrigatoria", models.BooleanField(default=False)),
                (
                    "tarja",
                    models.CharField(
                        choices=[
                            ("sem", "Sem tarja"),
                            ("vermelha", "Tarja vermelha"),
                            ("preta", "Tarja preta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="pessoa.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoSaida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_saida", models.DateField(auto_now_add=True)),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("venda", "Venda"),
                            ("perda", "Perda"),
                            ("devolucao", "Devolução"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saidas",
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateField(auto_now_add=True)),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_custo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "forma_aquisicao",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("devolucao", "Devolução"),
                            ("doacao", "Doação"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstoqueProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_lote", models.CharField(max_length=50)),
                ("data_validade", models.DateField()),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("local_armazenamento", models.CharField(max_length=100)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
    ]
