# Generated by Django 5.1.5 on 2025-04-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estoque", "0001_initial"),
        ("pessoa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("credito", "Cartão de Crédito"),
                            ("debito", "Cartão de Débito"),
                            ("pix", "Pix"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pessoa.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendaReceita",
            fields=[
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="vendas.venda",
                    ),
                ),
                ("nome_medico", models.CharField(max_length=255)),
                ("crm_uf", models.CharField(max_length=20, verbose_name="CRM e UF")),
                ("imagem_receita", models.ImageField(upload_to="receitas/")),
                ("data_prescricao", models.DateField()),
                ("medicamento_prescrito", models.TextField()),
                ("quantidade_prescrita", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="venda",
            name="produtos",
            field=models.ManyToManyField(
                through="vendas.ItemVenda", to="estoque.produto"
            ),
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendas.venda"
            ),
        ),
    ]
