# Generated by Django 5.1.5 on 2025-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("endereco", models.TextField(verbose_name="Endereço")),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=255, verbose_name="Nome Fantasia"),
                ),
                ("endereco", models.TextField(verbose_name="Endereço")),
            ],
        ),
    ]
